export const productsMockDate = [
  {
    id: 1,
    name: "Люстра Кристальная симфония",
    price: "20 000",
    materialBody: "Латунь",
    materialFacade: "Хрусталь",
    manufacturer: "Maytoni",
    productionTime: "14 дней",
    warranty: "2 года",
    lifting: true,
    assembly: true,
    article: "MY-L001",
    deliveryMoscow: "Бесплатно",
    deliveryDate: "2025-02-25",
    description: "Элегантная хрустальная люстра с 8 лампами",
    reviews: {
      average: 4.8,
      count: 56,
    },
    rating: 4.9,
    image: "https://example.com/images/crystal-symphony-chandelier.jpg",
  },
  {
    id: 2,
    name: "Люстра Модерн Арт",
    price: "20 000",

    materialBody: "Алюминий",
    materialFacade: "Стекло",
    manufacturer: "ST Luce",
    productionTime: "10 дней",
    warranty: "1 год",
    lifting: false,
    assembly: false,
    article: "STL-M002",
    deliveryMoscow: "1000 руб.",
    deliveryDate: "2025-02-21",
    description: "Современная люстра в стиле минимализм",
    reviews: {
      average: 4.5,
      count: 32,
    },
    rating: 4.6,
    image: "https://example.com/images/modern-art-chandelier.jpg",
  },
  {
    id: 3,
    name: "Люстра Классика Ренессанса",
    price: "20 000",

    materialBody: "Бронза",
    materialFacade: "Муранское стекло",
    manufacturer: "Ideal Lux",
    productionTime: "21 день",
    warranty: "3 года",
    lifting: true,
    assembly: true,
    article: "IL-C003",
    deliveryMoscow: "Бесплатно",
    deliveryDate: "2025-03-04",
    description: "Роскошная люстра в классическом стиле",
    reviews: {
      average: 4.9,
      count: 78,
    },
    rating: 5.0,
    image: "https://example.com/images/renaissance-classic-chandelier.jpg",
  },
  {
    id: 4,
    name: "Люстра Лофт Индастриал",
    price: "20 000",

    materialBody: "Металл",
    materialFacade: "Металл",
    manufacturer: "Velante",
    productionTime: "7 дней",
    warranty: "1 год",
    lifting: false,
    assembly: false,
    article: "VL-L004",
    deliveryMoscow: "500 руб.",
    deliveryDate: "2025-02-18",
    description: "Стильная люстра в индустриальном стиле",
    reviews: {
      average: 4.7,
      count: 45,
    },
    rating: 4.8,
    image: "https://example.com/images/loft-industrial-chandelier.jpg",
  },
  {
    id: 5,
    name: "Люстра Эко-Натурал",
    price: "20 000",

    materialBody: "Дерево",
    materialFacade: "Льняная ткань",
    manufacturer: "Eglo",
    productionTime: "14 дней",
    warranty: "2 года",
    lifting: true,
    assembly: true,
    article: "EG-E005",
    deliveryMoscow: "Бесплатно",
    deliveryDate: "2025-02-25",
    description: "Экологичная люстра из натуральных материалов",
    reviews: {
      average: 4.6,
      count: 39,
    },
    rating: 4.7,
    image: "https://example.com/images/eco-natural-chandelier.jpg",
  },
  {
    id: 6,
    name: "Люстра Хай-Тек Футуризм",
    price: "20 000",

    materialBody: "Хром",
    materialFacade: "Акрил",
    manufacturer: "Lightstar",
    productionTime: "10 дней",
    warranty: "2 года",
    lifting: false,
    assembly: true,
    article: "LS-H006",
    deliveryMoscow: "700 руб.",
    deliveryDate: "2025-02-21",
    description: "Футуристическая люстра в стиле хай-тек",
    reviews: {
      average: 4.8,
      count: 52,
    },
    rating: 4.9,
    image: "https://example.com/images/high-tech-futurism-chandelier.jpg",
  },
  {
    id: 7,
    name: "Люстра Винтаж Шик",
    price: "20 000",

    materialBody: "Латунь состаренная",
    materialFacade: "Стекло молочное",
    manufacturer: "Arte Lamp",
    productionTime: "18 дней",
    warranty: "2 года",
    lifting: true,
    assembly: true,
    article: "AL-V007",
    deliveryMoscow: "Бесплатно",
    deliveryDate: "2025-02-29",
    description: "Винтажная люстра с элегантным дизайном",
    reviews: {
      average: 4.7,
      count: 63,
    },
    rating: 4.8,
    image: "https://example.com/images/vintage-chic-chandelier.jpg",
  },
  {
    id: 8,
    name: "Люстра Скандинавский Минимализм",
    price: "20 000",

    materialBody: "Дуб",
    materialFacade: "Металл белый",
    manufacturer: "Nowodvorski",
    productionTime: "12 дней",
    warranty: "1 год",
    lifting: false,
    assembly: false,
    article: "NW-S008",
    deliveryMoscow: "600 руб.",
    deliveryDate: "2025-02-23",
    description: "Минималистичная люстра в скандинавском стиле",
    reviews: {
      average: 4.5,
      count: 41,
    },
    rating: 4.6,
    image: "https://example.com/images/scandinavian-minimalism-chandelier.jpg",
  },
  {
    id: 9,
    name: "Люстра Арт-Деко Гламур",
    price: "20 000",

    materialBody: "Золото",
    materialFacade: "Хрусталь",
    manufacturer: "Favourite",
    productionTime: "21 день",
    warranty: "3 года",
    lifting: true,
    assembly: true,
    article: "FV-A009",
    deliveryMoscow: "Бесплатно",
    deliveryDate: "2025-03-04",
    description: "Гламурная люстра в стиле арт-деко",
    reviews: {
      average: 4.9,
      count: 87,
    },
    rating: 5.0,
    image: "https://example.com/images/art-deco-glamour-chandelier.jpg",
  },
  {
    id: 10,
    name: "Люстра Эко-Тек Инновация",
    price: "20 000",

    materialBody: "Переработанный пластик",
    materialFacade: "Светодиодные панели",
    manufacturer: "Philips",
    productionTime: "15 дней",
    warranty: "5 лет",
    lifting: false,
    assembly: true,
    article: "PH-E010",
    deliveryMoscow: "800 руб.",
    deliveryDate: "2025-02-26",
    description: "Инновационная эко-френдли люстра с LED-технологией",
    reviews: {
      average: 4.7,
      count: 59,
    },
    rating: 4.8,
    image: "https://example.com/images/eco-tech-innovation-chandelier.jpg",
  },
];
